//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneClassesGeneration".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    public partial class SceneInfo
    {
		private static Dictionary<SceneId, SceneInfo> _registry = new Dictionary<SceneId, SceneInfo>()
        {
			{SceneId._01_DockingBay, new SceneInfo(SceneId._01_DockingBay, "01-DockingBay", SceneType.Room)},
			{SceneId._02_AirLockAccess, new SceneInfo(SceneId._02_AirLockAccess, "02-AirLockAccess", SceneType.Room)},
			{SceneId._03_AirLock, new SceneInfo(SceneId._03_AirLock, "03-AirLock", SceneType.Room)},
			{SceneId.Gameplay, new SceneInfo(SceneId.Gameplay, "Gameplay", SceneType.Gameplay)},
			{SceneId.MainMenu, new SceneInfo(SceneId.MainMenu, "MainMenu", SceneType.Screen)},
			{SceneId.MasterFrigate, new SceneInfo(SceneId.MasterFrigate, "MasterFrigate", SceneType.Master)},
			{SceneId.VentilationShaft, new SceneInfo(SceneId.VentilationShaft, "VentilationShaft", SceneType.Room)},
			            
        };
    }
}