//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneClassesGeneration".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    /// <summary>
    /// Enumeration identifying scenes in the system.
    /// </summary>
    public enum SceneId
    {
		MasterFrigate = 1,
		Gameplay = 10001,
		_01_DockingBay = 20001,
		_02_AirLockAccess = 20002,
		_03_AirLock = 20003,
		VentilationShaft = 20004,
		MainMenu = 30001,
		
    }
}