//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneInfoGenerator".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    public partial class SceneInfo
    {
		private static Dictionary<SceneId, SceneInfo> _registry = new Dictionary<SceneId, SceneInfo>()
        {
			{SceneId._01_Frigate_DockingBay, new SceneInfo(SceneId._01_Frigate_DockingBay, "01-Frigate-DockingBay", SceneType.Room)},
			{SceneId.Gameplay, new SceneInfo(SceneId.Gameplay, "Gameplay", SceneType.Gameplay)},
			{SceneId.MainMenu, new SceneInfo(SceneId.MainMenu, "MainMenu", SceneType.Room)},
			{SceneId.MasterFrigate, new SceneInfo(SceneId.MasterFrigate, "MasterFrigate", SceneType.Master)},
			            
        };
    }
}